float64 forearm_joint
float64 palm_axis_joint
float64 palm_l_joint

float64 thumb_axis_joint

float64 index_mcp
float64 index_pip
float64 index_dip

float64 middle_mcp
float64 middle_pip
float64 middle_dip

float64 ring_mcp
float64 ring_pip
float64 ring_dip

float64 small_mcp
float64 small_pip
float64 small_dip

float64 thumb_mcp
float64 thumb_pip
float64 thumb_dip

float64 len_index
float64 len_middle
float64 len_ring
float64 len_small
float64 len_thumb

float64 frc_index
float64 frc_middle
float64 frc_ring
float64 frc_thumb

float64 palm_range